from __future__ import annotations

from typing import Any, Optional, Protocol

import numpy as np


class FrameProvider(Protocol):
    current_source: str

    def read(self) -> np.ndarray: ...
    def prepare_switch(self, requested: Optional[str] = None) -> str: ...
    def commit_prepared_switch(self, expected_source: Optional[str] = None) -> str: ...
    def cancel_prepared_switch(self) -> None: ...
    def cleanup(self) -> None: ...
    def describe_source(self) -> str: ...


class Detector(Protocol):
    @property
    def is_ready(self) -> bool: ...

    @property
    def last_error(self) -> str: ...

    def ensure_ready(self) -> bool: ...
    def reload(self) -> bool: ...
    def predict(
        self,
        frame: np.ndarray,
        *,
        image_size: int,
        confidence: float,
        iou: float,
        max_det: int,
    ) -> list[Any]: ...


class Recognizer(Protocol):
    @property
    def load_error(self) -> Optional[str]: ...

    def ensure_loaded(self) -> bool: ...
    def embed(self, bgr_crop: np.ndarray) -> Optional[np.ndarray]: ...


class AiAnalyzer(Protocol):
    def analyze(
        self,
        capture: dict[str, Any],
        *,
        provider: str,
        prompt: str,
        model: str = "",
    ) -> tuple[str, str]: ...


class StateStore(Protocol):
    def verify_writable(self) -> None: ...
    def load_snapshot(self) -> dict[str, Any]: ...
    def save_snapshot(self, snapshot: dict[str, Any]) -> None: ...
    def append_recovery_event(self, event: dict[str, Any]) -> None: ...
    def load_recovery_log(self, limit: int = 50) -> list[dict[str, Any]]: ...
