"""Export a Nerfstudio Splatfacto checkpoint to Gaussian PLY without ns-export."""

from __future__ import annotations

import argparse
from collections import OrderedDict
from importlib.metadata import version
from pathlib import Path

import numpy as np
import torch

from nerfstudio.models.splatfacto import SplatfactoModel
from nerfstudio.utils.eval_utils import eval_setup


def export_gaussian_splat(load_config: Path, output_path: Path, *, ply_color_mode: str = "sh_coeffs") -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    _, pipeline, _, _ = eval_setup(load_config, test_mode="inference")
    if not isinstance(pipeline.model, SplatfactoModel):
        raise TypeError(f"Expected SplatfactoModel, got {type(pipeline.model).__name__}")

    model = pipeline.model
    map_to_tensors: OrderedDict[str, np.ndarray] = OrderedDict()
    with torch.no_grad():
        positions = model.means.cpu().numpy()
        count = positions.shape[0]
        n = count
        map_to_tensors["x"] = positions[:, 0]
        map_to_tensors["y"] = positions[:, 1]
        map_to_tensors["z"] = positions[:, 2]
        map_to_tensors["nx"] = np.zeros(n, dtype=np.float32)
        map_to_tensors["ny"] = np.zeros(n, dtype=np.float32)
        map_to_tensors["nz"] = np.zeros(n, dtype=np.float32)

        if ply_color_mode == "rgb":
            colors = torch.clamp(model.colors.clone(), 0.0, 1.0).data.cpu().numpy()
            colors = (colors * 255).astype(np.uint8)
            map_to_tensors["red"] = colors[:, 0]
            map_to_tensors["green"] = colors[:, 1]
            map_to_tensors["blue"] = colors[:, 2]
        else:
            shs_0 = model.shs_0.contiguous().cpu().numpy()
            for i in range(shs_0.shape[1]):
                map_to_tensors[f"f_dc_{i}"] = shs_0[:, i, None]

        if model.config.sh_degree > 0 and ply_color_mode == "sh_coeffs":
            shs_rest = model.shs_rest.transpose(1, 2).contiguous().cpu().numpy()
            shs_rest = shs_rest.reshape((n, -1))
            for i in range(shs_rest.shape[-1]):
                map_to_tensors[f"f_rest_{i}"] = shs_rest[:, i, None]

        map_to_tensors["opacity"] = model.opacities.data.cpu().numpy()
        scales = model.scales.data.cpu().numpy()
        for i in range(3):
            map_to_tensors[f"scale_{i}"] = scales[:, i, None]
        quats = model.quats.data.cpu().numpy()
        for i in range(4):
            map_to_tensors[f"rot_{i}"] = quats[:, i, None]

    select = np.ones(n, dtype=bool)
    for tensor in map_to_tensors.values():
        select = np.logical_and(select, np.isfinite(tensor).all(axis=-1))
    low_opacity = map_to_tensors["opacity"].squeeze(axis=-1) < -5.5373
    select[low_opacity] = False
    if np.sum(select) < n:
        for key, tensor in map_to_tensors.items():
            map_to_tensors[key] = tensor[select]
        count = int(np.sum(select))

    _write_ply(output_path, count, map_to_tensors)


def _write_ply(path: Path, count: int, map_to_tensors: OrderedDict[str, np.ndarray]) -> None:
    if not all(tensor.size == count for tensor in map_to_tensors.values()):
        raise ValueError("Count does not match the length of all tensors")
    with path.open("wb") as ply_file:
        ply_file.write(b"ply\n")
        ply_file.write(b"format binary_little_endian 1.0\n")
        ply_file.write(f"comment Generated by Nerfstudio {version('nerfstudio')}\n".encode())
        ply_file.write(b"comment Vertical Axis: z\n")
        ply_file.write(f"element vertex {count}\n".encode())
        for key, tensor in map_to_tensors.items():
            data_type = "float" if tensor.dtype.kind == "f" else "uchar"
            ply_file.write(f"property {data_type} {key}\n".encode())
        ply_file.write(b"end_header\n")
        for i in range(count):
            for tensor in map_to_tensors.values():
                value = tensor[i]
                if tensor.dtype.kind == "f":
                    ply_file.write(np.float32(value).tobytes())
                else:
                    ply_file.write(value.tobytes())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--load-config", required=True, type=Path)
    parser.add_argument("--output-path", required=True, type=Path)
    parser.add_argument("--ply-color-mode", choices=("sh_coeffs", "rgb"), default="sh_coeffs")
    args = parser.parse_args()
    export_gaussian_splat(args.load_config, args.output_path, ply_color_mode=args.ply_color_mode)


if __name__ == "__main__":
    main()

